# Enable C++ support in the build system
CONFIG_CPP=y
CONFIG_STD_CPP23=y

# Use the C++ standard library (e.g., std::string, std::vector)
CONFIG_REQUIRES_FULL_LIBCPP=y

# UART IRQ config
CONFIG_UART_INTERRUPT_DRIVEN=y

# RGB LED driver
CONFIG_SPI=y
CONFIG_LED_STRIP=y

# Bluetooth
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Server"

# Polling API
CONFIG_POLL=y

# Enable logging
CONFIG_LOG=y
CONFIG_BLESERIAL_LOG_LEVEL_DBG=y
CONFIG_HWSERIAL_LOG_LEVEL_DBG=y
